/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculadora_Calculadora */

#ifndef _Included_calculadora_Calculadora
#define _Included_calculadora_Calculadora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculadora_Calculadora
 * Method:    soma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculadora_Calculadora_soma
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
